`define OPERATION_WIDTH_CONFIG 4
`define SUPPORT_REPEAT_CONFIG
`define NUM_INSTRUCTION_CONFIG 4 //ischanged next line should change
`define PC_WIDTH_CONFIG 2
`define FLOAT_ALU_SUPPORT_CONFIG 
`define FLOAT_MULTIPLIER_SUPPORT_CONFIG 
`define FLOAT_ADDER_SUPPORT_CONFIG 
`define INTEGER_ADDER_SUPPORT_CONFIG
`define INTEGER_MULTIPLIER_SUPPORT_CONFIG
`define BITWISE_ALU_SUPPORT_CONFIG

 
