`define OPERATION_WIDTH_CONFIG 4
`define SUPPORT_REPEAT_CONFIG
`define NUM_INSTRUCTION_CONFIG 8 //ischanged next line should change
`define PC_WIDTH_CONFIG 8
`define GOLOBAL_DATA_BUS_WIDTH_CONFIG 32
`define INTEGER_ADDER_SUPPORT_CONFIG
`define INTEGER_MULTIPLIER_SUPPORT_CONFIG
`define BITWISE_ALU_SUPPORT_CONFIG 
`define  REG_TRANS_SRC_WIDTH_CONFIG 3
`define REG_TRANS_DST_WIDTH_CONFIG 3
//`define FLOAT_ALU_SUPPORT_CONFIG
//`define FLOAT_ADDER_SUPPORT_CONFIG
//`define FLOAT_MULTIPLIER_SUPPORT_CONFIG
`define LAYER_ID_WIDTH_CONFIG 3
`define SWITCH_ID_WIDTH_CONFIG 6
`define SWITCH_STATE_WIDTH_CONFIG 1

